[package]
name = "redpitaya"
description = "Crate to manipulate redpitaya"
license = "MIT"
version = "0.11.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
repository = "https://github.com/yellow-pitaya/api.git"
documentation = "https://docs.rs/redpitaya/"
keywords = ["redpitaya"]
categories = ["api-bindings", "hardware-support"]

[dependencies]
libc = "0.2"

[dependencies.rp-sys]
path = "rp-sys"
version = "0.14"

[badges]
travis-ci = { repository = "yellow-pitaya/api" }
gitlab = { repository = "yellow-pitaya/api" }
