[package]
name = "rp-sys"
version = "0.15.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
description = "FFI bindings to redpitaya API"
repository = "https://github.com/yellow-pitaya/api.git"
documentation = "https://docs.rs/rp-sys"
keywords = ["redpitaya"]
license = "MIT"
categories = ["external-ffi-bindings", "hardware-support"]

[dependencies]
libc="0.2"

[build-dependencies]
bindgen = "0.23"

[badges]
travis-ci = { repository = "yellow-pitaya/api" }
gitlab = { repository = "yellow-pitaya/api" }
